---
- hosts: localhost
  gather_facts: no
  connection: local 
  sudo: yes
  vars:
    bucketname: joey_deepdive
  tasks:
    - name: download file
      s3:
        bucket: "{{ bucketname }}"
        object: ecs.config
        dest: ecs.config1
        mode: get
