# Create a new Droplet
# Will return the droplet details including the droplet id (used for idempotence)
# sts
- hosts: local
  gather_facts: false
  tasks:
  - name: Create a new droplet
    digital_ocean:
      state: present
      command: droplet
      name: mynode01
      api_token: "{{apitoken}}"
      size_id: 2gb
      region_id: nyc3
      image_id: 22995941
      wait_timeout: 500
    register: my_do_node

  - name: Get the newly created droplet id
    debug:
      msg: "ID is {{ my_do_node.droplet.id }}"

  - name: Get the newly created droplet IP Address
    debug:
      msg: "IP is {{ my_do_node.droplet.ip_address }}"

