# Ensure a droplet is present
# If droplet id already exist, will return the droplet details and changed = False
# If no droplet matches the id, a new droplet will be created and the droplet details (including the new id) are returned, changed = True.
- hosts: local
  gather_facts: false
  tasks:
  - name: Delete a Droplet
    digital_ocean:
      state: deleted
      command: droplet
      id: 40676920
      name: mynode01
      api_token: "{{apitoken}}"
      size_id: 2gb
      region_id: nyc3
      image_id: 
      wait_timeout: 500
