# Create a new Droplet
# Will return the droplet details including the droplet id (used for idempotence)
# sts
- hosts: local
  gather_facts: false
  tasks:
  - name: Delete a droplet
    digital_ocean:
      state: deleted
      command: droplet
      name: mynode01
      api_token: "{{apitoken}}"
      size_id: 2gb
      region_id: nyc3
      image_id: 22995941

